# main configuration file
session: "cookie"
session_cookie_key: "circulation"
session_expires: "1 hour"

charset: "UTF-8"
template: template_toolkit

#layout: main
engines:
 template_toolkit:
  encoding:  'utf8'
  start_tag: '[%'
  end_tag:   '%]'
  ENCODING: "UTF-8"
  PRIVATE: 1
  TRIM: 1
  EVAL_PERL: 1
  ANYCASE: "no"
  WRAPPER: layouts/main.tt

record_resolver: &recordresolver
  package: "RecordResolver::UnAPI"
  options:
    baseurl: "http://search.ugent.be/meercat/x/unapi"
    docdel_libraries:
      - BIB
      - BIBA
      - BIBB
      - BIBC 
      - BIBD
      - BIBE 
      - BIBF
      - BIBE
      - BIBG
      - BIBH 
      - BIBI
      - BIBJ
      - BIBK
      - BIBL 
      - BIBM 
      - BIBN
      - K.KLDR
      - BLID
      - BHSL 
      - BRKZ
      - DEPA
      - DEPB 
      - DEPC
      - ALLW 
      - EBIB 
      - L32 
      - TBBS 
      - WLIW 
      - G00
      - L12 
      - L14H 
      - L14X 
      - L16 
      - L26 
      - L30 
      - L32 
      - L34 
      - L37 
      - L45 
      - L46 
      - L88
      - WLBW 
      - WE11A 
      - WE11B 
      - WEBIB 
      - DIBIB 
      - VLGMS 
      - VBS
availability_resolver: &availabilityresolver
  package: "RecordResolver::Availability"
  options:
    baseurl: "http://aleph.ugent.be/cgi-bin/loan/check_status.cgi"
  
private_routes:
  - "/request"
plugins:  
  Lexicon:    
    namespace: "Circulation::Lexicon"
    path: languages
    auto_detect: 1
    default: nl
    func: [l, _]
    session_name: lang
    param_name: lang
    langs:
     en: English
     nl: Nederlands

  Auth::RBAC:
    credentials:
      class: LDAP
      options:
        whitelist:
          - njfranck
          - cjsteven 
          - oreygaer 
          - fvdfraen 
          - adefleyt 
        secure: 1
        host: "ldaps.ugent.be"
        args_to_new:
          timeout: 3
          port: 636
        applications_base: "ugentID=870910100341,ou=applications,dc=ugent,dc=be"
        applications_password: "{b1bb1b}"
        auth_base: "ugentID=%s,ou=people,dc=UGent,dc=be"
        auth_attr: ugentid
        search_filter: "(uid=%s)"
        search_base: "ou=people,dc=ugent,dc=be"
        search_scope: "one"
        search_attrs: 
          - ugentID 
          - uid   
          - ugentpreferredsn 
          - ugentpreferredgivenname 
          - mail 
          - departmentnumber 
          - objectclass
          - personnumber
        id_attr: uid
        name_attr: uid
        login_attr: uid
        roles_attr: objectclass
    permissions:
      class: Config
      options:
        control:
          admin:
            permissions:
              manage_accounts:
                operations:
                  - view
                  - create
                  - update
                  - delete
          user:
            permissions:
              manage_accounts:
                operations:
                  - view
                  - create
          guests:
            permissions:
              manage_accounts:
                operations:
                  - view
